import { BUSINESS } from './business';
import type { LegalDocument } from './types';

/**
 * Site identification — "mentions légales".
 *
 * Required of anyone publishing a site to the public in France (LCEN art. 6-III)
 * and across the EU (e-commerce directive art. 5), and required of an individual
 * publisher too, not only of companies. It is also the page a regulator or an
 * upset user looks for first, and its absence is the cheapest thing to be caught
 * on.
 */
export const NOTICE: LegalDocument = {
    slug: 'legal-notice',
    title: { en: 'Legal Notice', fr: 'Mentions légales' },
    intro: {
        en: 'Who publishes this site, and who hosts it.',
        fr: 'Qui publie ce site, et qui l’héberge.',
    },
    sections: [
        {
            heading: { en: 'Publisher', fr: 'Éditeur' },
            blocks: [{
                table: {
                    head: [{ en: 'Field', fr: 'Champ' }, { en: 'Detail', fr: 'Information' }],
                    rows: [
                        [{ en: 'Service', fr: 'Service' }, { en: BUSINESS.serviceName, fr: BUSINESS.serviceName }],
                        [{ en: 'Published by', fr: 'Édité par' }, { en: BUSINESS.operator, fr: BUSINESS.operator }],
                        [{ en: 'Address', fr: 'Adresse' }, { en: BUSINESS.address, fr: BUSINESS.address }],
                        [{ en: 'Country of establishment', fr: 'Pays d’établissement' }, { en: BUSINESS.country, fr: BUSINESS.country }],
                        [{ en: 'Contact', fr: 'Contact' }, { en: BUSINESS.email, fr: BUSINESS.email }],
                        [{ en: 'Publication director', fr: 'Directeur de la publication' }, { en: BUSINESS.publicationDirector, fr: BUSINESS.publicationDirector }],
                        [
                            { en: 'Business registration', fr: 'Immatriculation' },
                            {
                                en: BUSINESS.registration ?? 'Not registered as a business at the date of this notice.',
                                fr: BUSINESS.registration ?? 'Non immatriculé à la date des présentes mentions.',
                            },
                        ],
                    ],
                },
            }],
        },
        {
            heading: { en: 'Host', fr: 'Hébergeur' },
            blocks: [{
                p: {
                    en: `${BUSINESS.host.name}, ${BUSINESS.host.address} — ${BUSINESS.host.website}. Application data is stored in ${BUSINESS.dataRegion}.`,
                    fr: `${BUSINESS.host.name}, ${BUSINESS.host.address} — ${BUSINESS.host.website}. Les données de l’application sont stockées en ${BUSINESS.dataRegion}.`,
                },
            }],
        },
        {
            heading: { en: 'Images', fr: 'Images' },
            blocks: [{
                p: {
                    en: 'The photographs on the public pages come from Unsplash and are used under the Unsplash Licence, which permits commercial use without attribution. The 3D scene on the home page is generated by the site itself and uses no external model or asset. The body models are derived from MakeHuman assets released under CC0.',
                    fr: 'Les photographies des pages publiques proviennent d’Unsplash et sont utilisées sous licence Unsplash, qui autorise l’usage commercial sans attribution. La scène 3D de la page d’accueil est générée par le site lui-même, sans modèle ni ressource externe. Les modèles corporels sont dérivés de ressources MakeHuman publiées sous CC0.',
                },
            }],
        },
    ],
};
