import { BUSINESS } from './business';
import type { LegalDocument } from './types';

export const TERMS: LegalDocument = {
    slug: 'terms',
    title: { en: 'Terms of Service', fr: 'Conditions générales d’utilisation' },
    intro: {
        en: 'The agreement between you and us when you use SportMind.',
        fr: 'Le contrat entre vous et nous lorsque vous utilisez SportMind.',
    },
    sections: [
        {
            heading: { en: 'Who you are contracting with', fr: 'Avec qui vous contractez' },
            blocks: [{
                p: {
                    en: `SportMind AI is operated by ${BUSINESS.operator}, ${BUSINESS.address}, ${BUSINESS.country} (“we”). Using the service means you accept these terms.`,
                    fr: `SportMind AI est exploité par ${BUSINESS.operator}, ${BUSINESS.address}, ${BUSINESS.country} (« nous »). Utiliser le service vaut acceptation des présentes conditions.`,
                },
            }],
        },
        {
            heading: { en: 'What the service is', fr: 'Ce qu’est le service' },
            blocks: [
                {
                    p: {
                        en: 'SportMind records your training, nutrition and body measurements and produces plans and feedback from them, some of it generated by AI models. It is a training tool.',
                        fr: 'SportMind enregistre vos entraînements, votre nutrition et vos mensurations, et en tire des plans et des retours, en partie générés par des modèles d’IA. C’est un outil d’entraînement.',
                    },
                },
                {
                    callout: {
                        en: 'It is not a medical device and gives no medical, dietary or physiotherapy advice. It does not diagnose, treat or prevent anything. Output can be wrong. You are responsible for what you do with it, and you should speak to a qualified professional before changing how you train or eat — especially if you are injured, ill, pregnant, under treatment, or have a heart, metabolic or eating disorder.',
                        fr: 'Ce n’est pas un dispositif médical et il ne délivre aucun avis médical, diététique ou de kinésithérapie. Il ne diagnostique, ne traite et ne prévient rien. Les résultats peuvent être erronés. Vous êtes responsable de l’usage que vous en faites et devez consulter un professionnel qualifié avant de modifier votre entraînement ou votre alimentation — en particulier en cas de blessure, de maladie, de grossesse, de traitement en cours, ou de trouble cardiaque, métabolique ou du comportement alimentaire.',
                    },
                },
            ],
        },
        {
            heading: { en: 'Your account', fr: 'Votre compte' },
            blocks: [{
                list: [
                    { en: 'You must be 16 or older.', fr: 'Vous devez avoir 16 ans ou plus.' },
                    { en: 'Give accurate information and keep it up to date. Wrong height or weight produces wrong plans.', fr: 'Fournissez des informations exactes et tenez-les à jour. Une taille ou un poids erroné produit des plans erronés.' },
                    { en: 'Keep your password to yourself. Tell us if you think someone else has it.', fr: 'Gardez votre mot de passe pour vous. Prévenez-nous si vous pensez qu’il a été compromis.' },
                    { en: 'One account per person.', fr: 'Un seul compte par personne.' },
                ],
            }],
        },
        {
            heading: { en: 'What you may not do', fr: 'Ce qui est interdit' },
            blocks: [{
                list: [
                    { en: 'Upload anything you do not have the right to upload, including video of other people who have not agreed to it.', fr: 'Téléverser ce que vous n’avez pas le droit de téléverser, y compris des vidéos de tiers n’ayant pas donné leur accord.' },
                    { en: 'Harass, threaten or abuse anyone through the messaging or team features.', fr: 'Harceler, menacer ou insulter quiconque via la messagerie ou les fonctions d’équipe.' },
                    { en: 'Try to break, overload, scrape or reverse-engineer the service.', fr: 'Tenter de casser, surcharger, aspirer ou rétro-concevoir le service.' },
                    { en: 'Use it to give medical or clinical advice to other people.', fr: 'L’utiliser pour délivrer des conseils médicaux ou cliniques à autrui.' },
                ],
            }],
        },
        {
            heading: { en: 'What you upload stays yours', fr: 'Ce que vous téléversez reste à vous' },
            blocks: [{
                p: {
                    en: 'You keep every right in your videos, photos, measurements and messages. You give us only the permission we need to run the service for you: to store your content, show it back to you, share it with a coach or team you have joined, and send it to the AI model when you ask for an analysis. That permission ends when you delete the content or your account.',
                    fr: 'Vous conservez tous vos droits sur vos vidéos, photos, mensurations et messages. Vous nous accordez uniquement l’autorisation nécessaire au fonctionnement du service : stocker vos contenus, vous les restituer, les partager avec un entraîneur ou une équipe que vous avez rejointe, et les transmettre au modèle d’IA lorsque vous demandez une analyse. Cette autorisation prend fin à la suppression du contenu ou du compte.',
                },
            }],
        },
        {
            heading: { en: 'Paid plans', fr: 'Offres payantes' },
            blocks: [{
                p: {
                    en: 'Some features require a Pro plan, arranged with us directly. Prices, billing period and payment method are agreed with you before you pay. Your cancellation and refund rights are set out in the Refund Policy, which forms part of these terms.',
                    fr: 'Certaines fonctionnalités nécessitent une offre Pro, convenue directement avec nous. Le prix, la périodicité et le moyen de paiement vous sont communiqués avant tout paiement. Vos droits d’annulation et de remboursement figurent dans la Politique de remboursement, qui fait partie des présentes conditions.',
                },
            }],
        },
        {
            heading: { en: 'Availability, and what we are liable for', fr: 'Disponibilité et responsabilité' },
            blocks: [
                {
                    p: {
                        en: 'We try to keep the service running and your data safe, but we do not promise it will always be available or error-free. We may change or withdraw features.',
                        fr: 'Nous nous efforçons d’assurer la continuité du service et la sécurité de vos données, sans garantir une disponibilité permanente ni l’absence d’erreurs. Nous pouvons modifier ou retirer des fonctionnalités.',
                    },
                },
                {
                    p: {
                        en: 'We are liable for harm we cause you by breaking this agreement or by negligence. We are not liable for what you decide to do with a plan or an analysis, for injury sustained while training, or for loss caused by something outside our reasonable control. Nothing here limits liability that the law does not allow us to limit — including death or personal injury caused by our negligence, and fraud.',
                        fr: 'Nous sommes responsables des dommages que nous vous causons en manquant à ce contrat ou par négligence. Nous ne sommes pas responsables de ce que vous décidez de faire d’un plan ou d’une analyse, des blessures survenues à l’entraînement, ni des pertes dues à une cause échappant à notre contrôle raisonnable. Rien ici ne limite une responsabilité que la loi interdit de limiter — notamment le décès ou les dommages corporels causés par notre négligence, et la fraude.',
                    },
                },
            ],
        },
        {
            heading: { en: 'Ending it', fr: 'Fin du contrat' },
            blocks: [{
                p: {
                    en: 'You can delete your account whenever you like. We may suspend or close an account that breaks these terms, and we will tell you why unless the law prevents us.',
                    fr: 'Vous pouvez supprimer votre compte à tout moment. Nous pouvons suspendre ou fermer un compte qui enfreint ces conditions, en vous en indiquant le motif sauf interdiction légale.',
                },
            }],
        },
        {
            heading: { en: 'Law and disputes', fr: 'Droit applicable et litiges' },
            blocks: [
                {
                    p: {
                        en: 'Tunisian law governs this agreement. If you are a consumer resident in the European Union, this does not deprive you of the protection of the mandatory rules of your own country, and you may bring proceedings before your local courts.',
                        fr: 'Le droit tunisien régit le présent contrat. Si vous êtes un consommateur résidant dans l’Union européenne, cela ne vous prive pas de la protection des règles impératives de votre pays, et vous pouvez saisir les juridictions de votre lieu de résidence.',
                    },
                },
                {
                    p: {
                        en: `Talk to us first: ${BUSINESS.email}. Consumers in the EU may also use the European Commission’s online dispute resolution platform at ec.europa.eu/consumers/odr.`,
                        fr: `Contactez-nous d’abord : ${BUSINESS.email}. Les consommateurs de l’UE peuvent aussi recourir à la plateforme de règlement en ligne des litiges de la Commission européenne : ec.europa.eu/consumers/odr.`,
                    },
                },
                {
                    p: {
                        en: `Last updated ${BUSINESS.lastUpdated}.`,
                        fr: `Dernière mise à jour : ${BUSINESS.lastUpdated}.`,
                    },
                },
            ],
        },
    ],
};
